// Generated by tools/gen-script-examples.mjs from unity/runner-template/Assets/Runner/Tests/Scripts/*.lua: do not edit by hand.
// The example games the Unity tests play, as text, for the prompt (prompts.ts) and for the checks (examples.test.ts keeps this equal to the files).
export const EXAMPLE_GAMES: Readonly<Record<string, string>> = {
  catcher: `-- Catcher (2D). Drag to move the basket; catch the apples and avoid the bombs. Catch 15 apples to win.
-- A bomb or a missed apple costs one of your three lives.

local TARGET = 15
local basket

local function show()
  ui.text("score", "Apples " .. game.score .. " / " .. TARGET, { x = 0.05, y = 0.04, size = 0.045, color = 5 })
  ui.bar("lives", game.lives, 3, { x = 0.05, y = 0.1, w = 0.3, h = 0.025, color = 2 })
end

local function lose_life()
  game.lives = game.lives - 1
  show()
  if game.lives <= 0 then
    game.lose("Out of lives")
  end
end

local function drop()
  local bomb = rand() < 0.25
  local kind = "apple"
  local color = 3
  if bomb then
    kind = "bomb"
    color = 4
  end
  world.spawn("sphere", { x = rand() * 7 - 3.5, y = 9, w = 0.9, h = 0.9, vy = -(3.5 + game.time * 0.08), color = color, solid = true, tag = kind })
end

function init()
  world.bounds(9, 16)
  world.camera{ mode = "side2d" }
  basket = world.spawn("box", { x = 0, y = -6.5, w = 2, h = 0.8, color = 1, solid = true, tag = "basket" })
  game.lives = 3
  timer.every(0.8, drop)
  show()
end

function on_hold(x, y)
  basket.x = math.max(-3.5, math.min(3.5, x))
end

function on_collide(a, b)
  local item
  if a.tag == "basket" then
    item = b
  elseif b.tag == "basket" then
    item = a
  end
  if not item then
    return
  end
  item:destroy()
  if item.tag == "apple" then
    game.score = game.score + 1
    show()
    if game.score >= TARGET then
      game.win("All caught!")
    end
  elseif item.tag == "bomb" then
    lose_life()
  end
end

function on_exit(obj)
  if obj.tag == "apple" then
    lose_life()
  end
  if obj.tag ~= "basket" then
    obj:destroy()
  end
end
`,
  flier: `-- Flier (2D). Tap to flap and fly through the gaps between the pipes. Pass 10 pipes to win; touching a pipe or the edge loses.

local TARGET = 10
local GAP = 5.2
local bird

local function show()
  ui.text("score", "Pipes " .. game.score .. " / " .. TARGET, { x = 0.5, y = 0.05, size = 0.05, align = "center", color = 5 })
end

local function spawn_pipes()
  local center = rand() * 6 - 3
  local top = center + GAP / 2
  local bottom = center - GAP / 2
  world.spawn("box", { x = 6, y = (top + 10) / 2, w = 1.6, h = 10 - top, vx = -3.2, color = 3, solid = true, tag = "pipe" })
  world.spawn("box", { x = 6, y = (bottom - 10) / 2, w = 1.6, h = bottom + 10, vx = -3.2, color = 3, solid = true, tag = "pipe_low" })
end

function init()
  world.bounds(9, 16)
  world.gravity(24)
  world.camera{ mode = "side2d" }
  bird = world.spawn("sphere", { x = -2, y = 0, w = 0.9, h = 0.9, color = 2, gravity = true, solid = true, tag = "bird" })
  timer.every(1.5, spawn_pipes)
  show()
end

function update(dt)
  if bird.y < -8 or bird.y > 8 then
    game.lose("You hit the edge")
  end
end

function on_tap()
  bird.vy = 8.5
end

function on_collide(a, b)
  if a.tag == "bird" or b.tag == "bird" then
    game.lose("You hit a pipe")
  end
end

function on_exit(obj)
  if obj.tag == "bird" then
    return
  end
  if obj.tag == "pipe_low" then
    game.score = game.score + 1
    show()
    if game.score >= TARGET then
      game.win("You flew through!")
    end
  end
  obj:destroy()
end
`,
  runner: `-- Lane runner (3D, chase camera). Tap the left or right half of the screen to change lane and dodge the rocks.
-- Survive 30 seconds to win. You have three lives; a rock that hits you costs one.

local LANES = { -2.5, 0, 2.5 }
local SURVIVE = 30
local lane = 2
local player
local speed = 7

local function show()
  ui.text("score", "Dodged " .. game.score, { x = 0.05, y = 0.04, size = 0.04, color = 5 })
  ui.bar("lives", game.lives, 3, { x = 0.05, y = 0.1, w = 0.3, h = 0.025, color = 2 })
end

local function spawn_rock()
  local l = rand_int(1, 3)
  world.spawn("box", { x = LANES[l], y = 9, w = 1.4, h = 1.4, d = 1.4, vy = -speed, color = 4, solid = true, tag = "rock" })
end

function init()
  world.bounds(9, 16)
  player = world.spawn("box", { x = LANES[lane], y = -6, w = 1.2, h = 1.2, d = 1.2, color = 1, solid = true, tag = "player" })
  world.camera{ mode = "chase", follow = player }
  game.lives = 3
  timer.every(0.7, spawn_rock)
  show()
end

function update(dt)
  speed = 7 + game.time * 0.1
  if game.time >= SURVIVE then
    game.win("You made it!")
  end
end

function on_tap(x, y)
  if x < 0 then
    lane = math.max(1, lane - 1)
  else
    lane = math.min(3, lane + 1)
  end
  player.x = LANES[lane]
end

function on_collide(a, b)
  local rock
  if a.tag == "rock" and b.tag == "player" then
    rock = a
  elseif b.tag == "rock" and a.tag == "player" then
    rock = b
  end
  if not rock then
    return
  end
  rock:destroy()
  game.lives = game.lives - 1
  show()
  if game.lives <= 0 then
    game.lose("You crashed")
  end
end

function on_exit(obj)
  if obj.tag == "rock" then
    obj:destroy()
    game.score = game.score + 1
    show()
  end
end
`,
};
