// Generated by tools/gen-script-examples.mjs from unity/runner-template/Assets/Runner/Tests/Scripts/*.lua: do not edit by hand.
// The example games the Unity tests play, as text, for the prompt (prompts.ts) and for the checks (examples.test.ts keeps this equal to the files).
export const EXAMPLE_GAMES: Readonly<Record<string, string>> = {
  breaker: `-- Breaker (2D). Drag to move the paddle and bounce the ball into the bricks. Break them all to win.
-- Letting the ball fall past the paddle costs one of your three lives.

local paddle
local ball
local bricks = 0

local function show()
  ui.text("score", "Bricks " .. game.score, { x = 0.05, y = 0.04, size = 0.045, color = 5 })
  ui.bar("lives", game.lives, 3, { x = 0.05, y = 0.1, w = 0.3, h = 0.025, color = 2 })
end

local function serve()
  ball.x = 0
  ball.y = -5
  ball.vx = 3
  ball.vy = 7
end

function init()
  world.bounds(9, 16)
  world.camera{ mode = "side2d" }
  paddle = world.spawn("box", { x = 0, y = -7, w = 2, h = 0.5, d = 0.05, color = 1, solid = true, tag = "paddle" })
  ball = world.spawn("sphere", { x = 0, y = -5, w = 0.5, h = 0.5, d = 0.05, color = 5, solid = true, tag = "ball" })
  serve()
  for row = 0, 3 do
    for col = 0, 5 do
      world.spawn("box", { x = -3.75 + col * 1.5, y = 4 + row * 0.8, w = 1.3, h = 0.6, d = 0.05, color = 2 + row % 3, solid = true, tag = "brick" })
      bricks = bricks + 1
    end
  end
  game.lives = 3
  show()
end

function update(dt)
  if ball.x < -4.25 then
    ball.x = -4.25
    ball.vx = math.abs(ball.vx)
  elseif ball.x > 4.25 then
    ball.x = 4.25
    ball.vx = -math.abs(ball.vx)
  end
  if ball.y > 7.75 then
    ball.y = 7.75
    ball.vy = -math.abs(ball.vy)
  end
  if ball.y < -8.5 then
    game.lives = game.lives - 1
    show()
    if game.lives <= 0 then
      game.lose("Out of balls")
    else
      serve()
    end
  end
end

function on_hold(x, y)
  paddle.x = math.max(-3.5, math.min(3.5, x))
end

function on_collide(a, b)
  local other
  if a.tag == "ball" then
    other = b
  elseif b.tag == "ball" then
    other = a
  end
  if not other then
    return
  end
  if other.tag == "paddle" then
    ball.vy = math.abs(ball.vy)
    ball.vx = (ball.x - paddle.x) * 3
  elseif other.tag == "brick" then
    other:destroy()
    ball.vy = -ball.vy
    game.score = game.score + 1
    bricks = bricks - 1
    show()
    if bricks == 0 then
      game.win("Every brick!")
    end
  end
end
`,
  catcher: `-- Catcher (2D). Drag to move the basket; catch the apples and avoid the bombs. Catch 15 apples to win.
-- A bomb or a missed apple costs one of your three lives.

local TARGET = 15
local basket

local function show()
  ui.text("score", "Apples " .. game.score .. " / " .. TARGET, { x = 0.05, y = 0.04, size = 0.045, color = 5 })
  ui.bar("lives", game.lives, 3, { x = 0.05, y = 0.1, w = 0.3, h = 0.025, color = 2 })
end

local function lose_life()
  game.lives = game.lives - 1
  show()
  if game.lives <= 0 then
    game.lose("Out of lives")
  end
end

local function drop()
  local bomb = rand() < 0.25
  local kind = "apple"
  local color = 3
  if bomb then
    kind = "bomb"
    color = 4
  end
  world.spawn("sphere", { x = rand() * 7 - 3.5, y = 9, w = 0.9, h = 0.9, vy = -(3.5 + game.time * 0.08), color = color, solid = true, tag = kind })
end

function init()
  world.bounds(9, 16)
  world.camera{ mode = "side2d" }
  basket = world.spawn("box", { x = 0, y = -6.5, w = 2, h = 0.8, color = 1, solid = true, tag = "basket" })
  game.lives = 3
  timer.every(0.8, drop)
  show()
end

function on_hold(x, y)
  basket.x = math.max(-3.5, math.min(3.5, x))
end

function on_collide(a, b)
  local item
  if a.tag == "basket" then
    item = b
  elseif b.tag == "basket" then
    item = a
  end
  if not item then
    return
  end
  item:destroy()
  if item.tag == "apple" then
    game.score = game.score + 1
    show()
    if game.score >= TARGET then
      game.win("All caught!")
    end
  elseif item.tag == "bomb" then
    lose_life()
  end
end

function on_exit(obj)
  if obj.tag == "apple" then
    lose_life()
  end
  if obj.tag ~= "basket" then
    obj:destroy()
  end
end
`,
  dodger: `-- Dodger (2D, endless). Hold and drag to steer under the falling rocks; they get faster. Survive 45 seconds to win.
-- One hit and it is over. The score is the seconds you lasted.

local SURVIVE = 45
local player

local function drop()
  local size = 0.8 + rand() * 1.2
  world.spawn("sphere", { x = rand() * 8 - 4, y = 9, w = size, h = size, d = 0.05, vy = -(4 + game.time * 0.12), color = 4, solid = true, tag = "rock" })
end

function init()
  world.bounds(9, 16)
  world.camera{ mode = "side2d" }
  player = world.spawn("box", { x = 0, y = -6.5, w = 1, h = 1, d = 0.05, color = 1, solid = true, tag = "player" })
  timer.every(0.45, drop)
end

function update(dt)
  game.score = math.floor(game.time)
  ui.text("score", "Seconds " .. game.score .. " / " .. SURVIVE, { x = 0.05, y = 0.04, size = 0.045, color = 5 })
  if game.time >= SURVIVE then
    game.win("You lasted!")
  end
end

function on_hold(x, y)
  player.x = math.max(-4, math.min(4, x))
end

function on_collide(a, b)
  if a.tag == "player" or b.tag == "player" then
    game.lose("Hit by a rock")
  end
end

function on_exit(obj)
  if obj.tag == "rock" then
    obj:destroy()
  end
end
`,
  flier: `-- Flier (2D). Tap to flap and fly through the gaps between the pipes. Pass 10 pipes to win; touching a pipe or the edge loses.

local TARGET = 10
local GAP = 5.2
local bird

local function show()
  ui.text("score", "Pipes " .. game.score .. " / " .. TARGET, { x = 0.5, y = 0.05, size = 0.05, align = "center", color = 5 })
end

local function spawn_pipes()
  local center = rand() * 6 - 3
  local top = center + GAP / 2
  local bottom = center - GAP / 2
  world.spawn("box", { x = 6, y = (top + 10) / 2, w = 1.6, h = 10 - top, vx = -3.2, color = 3, solid = true, tag = "pipe" })
  world.spawn("box", { x = 6, y = (bottom - 10) / 2, w = 1.6, h = bottom + 10, vx = -3.2, color = 3, solid = true, tag = "pipe_low" })
end

function init()
  world.bounds(9, 16)
  world.gravity(24)
  world.camera{ mode = "side2d" }
  bird = world.spawn("sphere", { x = -2, y = 0, w = 0.9, h = 0.9, color = 2, gravity = true, solid = true, tag = "bird" })
  timer.every(1.5, spawn_pipes)
  show()
end

function update(dt)
  if bird.y < -8 or bird.y > 8 then
    game.lose("You hit the edge")
  end
end

function on_tap()
  bird.vy = 8.5
end

function on_collide(a, b)
  if a.tag == "bird" or b.tag == "bird" then
    game.lose("You hit a pipe")
  end
end

function on_exit(obj)
  if obj.tag == "bird" then
    return
  end
  if obj.tag == "pipe_low" then
    game.score = game.score + 1
    show()
    if game.score >= TARGET then
      game.win("You flew through!")
    end
  end
  obj:destroy()
end
`,
  memory: `-- Memory (2D puzzle). Watch the tiles light up, then tap them in the same order. Each round adds one more. Repeat 5 in a row to win.
-- (sequence, showing and at are globals only so that a test can watch the game.)

local COLORS = { 2, 3, 4, 5 }
local tiles = {}
sequence = {}
showing = true
at = 1

local function flash(i)
  tiles[i]:set_color(1)
  timer.after(0.3, function()
    tiles[i]:set_color(COLORS[i])
  end)
end

local function play_sequence()
  showing = true
  ui.text("hint", "Watch", { x = 0.5, y = 0.12, size = 0.05, align = "center", color = 5 })
  for i = 1, #sequence do
    timer.after(0.6 * i, function()
      flash(sequence[i])
    end)
  end
  timer.after(0.6 * (#sequence + 1), function()
    showing = false
    at = 1
    ui.text("hint", "Your turn", { x = 0.5, y = 0.12, size = 0.05, align = "center", color = 5 })
  end)
end

local function next_round()
  sequence[#sequence + 1] = rand_int(1, 4)
  game.score = #sequence - 1
  ui.text("score", "Round " .. #sequence .. " / 5", { x = 0.5, y = 0.05, size = 0.05, align = "center", color = 5 })
  timer.after(0.8, play_sequence)
end

local function tile_at(x, y)
  for i, t in ipairs(tiles) do
    if math.abs(x - t.x) < t.w / 2 and math.abs(y - t.y) < t.h / 2 then
      return i
    end
  end
end

function init()
  world.bounds(9, 16)
  world.camera{ mode = "side2d" }
  local spots = { { -2, 2 }, { 2, 2 }, { -2, -2 }, { 2, -2 } }
  for i = 1, 4 do
    tiles[i] = world.spawn("quad", { x = spots[i][1], y = spots[i][2], w = 3.5, h = 3.5, color = COLORS[i], tag = "tile" })
  end
  next_round()
end

function on_tap(x, y)
  if showing then
    return
  end
  local i = tile_at(x, y)
  if not i then
    return
  end
  flash(i)
  if i ~= sequence[at] then
    game.lose("Wrong tile")
    return
  end
  at = at + 1
  if at > #sequence then
    showing = true
    if #sequence >= 5 then
      game.score = 5
      game.win("Great memory!")
    else
      next_round()
    end
  end
end
`,
  platformer: `-- Platformer (2D). Hold to run toward your finger, tap to jump. Collect all 5 coins to win; falling off the bottom loses.
-- The world has no floors of its own, so update() lands the hero on a platform by hand.

local hero
local on_ground = false
local platforms = {}

local function platform(x, y, w)
  platforms[#platforms + 1] = world.spawn("box", { x = x, y = y, w = w, h = 0.6, d = 0.05, color = 2, tag = "platform" })
end

local function coin(x, y)
  world.spawn("sphere", { x = x, y = y, w = 0.6, h = 0.6, d = 0.05, color = 3, solid = true, tag = "coin" })
end

function init()
  world.bounds(9, 16)
  world.gravity(28)
  world.camera{ mode = "side2d" }
  hero = world.spawn("box", { x = -3, y = -2, w = 0.8, h = 1.2, d = 0.05, color = 1, gravity = true, solid = true, tag = "hero" })
  platform(-3, -4, 4)
  platform(0, -2, 3)
  platform(3, 0, 3)
  platform(0, 2, 3)
  platform(-3, 4, 4)
  coin(0, -1.2)
  coin(3, 0.8)
  coin(0, 2.8)
  coin(-3, 4.8)
  coin(-3, -3.2)
end

function update(dt)
  on_ground = false
  if hero.vy <= 0 then
    local feet = hero.y - hero.h / 2
    for _, p in ipairs(platforms) do
      local top = p.y + p.h / 2
      if math.abs(hero.x - p.x) < (p.w + hero.w) / 2 and feet <= top and feet >= top - 0.6 then
        hero.y = top + hero.h / 2
        hero.vy = 0
        on_ground = true
      end
    end
  end
  if not input.down then
    hero.vx = 0
  end
  if hero.y < -9 then
    game.lose("You fell")
  end
end

function on_hold(x, y)
  hero.vx = math.max(-5, math.min(5, (x - hero.x) * 4))
end

function on_tap(x, y)
  if on_ground then
    hero.vy = 12
  end
end

function on_collide(a, b)
  local c
  if a.tag == "coin" and b.tag == "hero" then
    c = a
  elseif b.tag == "coin" and a.tag == "hero" then
    c = b
  end
  if c then
    c:destroy()
    game.score = game.score + 1
    ui.text("score", "Coins " .. game.score .. " / 5", { x = 0.05, y = 0.04, size = 0.045, color = 5 })
    if game.score >= 5 then
      game.win("All the coins!")
    end
  end
end
`,
  rhythm: `-- Rhythm (2D). Notes fall down three lanes: tap the lane when a note reaches the line. Hit 20 notes to win.
-- Five misses (a note that gets past the line, or a tap with no note) lose.

local LANES = { -2.5, 0, 2.5 }
local LINE_Y = -6
local TARGET = 20
local misses = 0

local function show()
  ui.text("score", "Notes " .. game.score .. " / " .. TARGET, { x = 0.05, y = 0.04, size = 0.045, color = 5 })
  ui.bar("misses", 5 - misses, 5, { x = 0.05, y = 0.1, w = 0.3, h = 0.025, color = 2 })
end

local function miss()
  misses = misses + 1
  show()
  if misses >= 5 then
    game.lose("Too many misses")
  end
end

local function spawn_note()
  local lane = rand_int(1, 3)
  local note = world.spawn("box", { x = LANES[lane], y = 9, w = 1.6, h = 0.6, d = 0.05, vy = -6, color = 2 + lane, tag = "note" })
  note.lane = lane
end

function init()
  world.bounds(9, 16)
  world.camera{ mode = "side2d" }
  world.spawn("box", { x = 0, y = LINE_Y, z = 1, w = 8, h = 0.15, d = 0.05, color = 5 })
  timer.every(0.7, spawn_note)
  show()
end

function on_tap(x, y)
  local lane = 2
  if x < -1.25 then
    lane = 1
  elseif x > 1.25 then
    lane = 3
  end
  for _, note in ipairs(world.find("note")) do
    if note.lane == lane and math.abs(note.y - LINE_Y) < 0.9 then
      note:destroy()
      game.score = game.score + 1
      show()
      if game.score >= TARGET then
        game.win("Perfect rhythm!")
      end
      return
    end
  end
  miss()
end

function on_exit(obj)
  if obj.tag == "note" then
    miss()
  end
  obj:destroy()
end
`,
  runner: `-- Lane runner (3D, chase camera). Tap the left or right half of the screen to change lane and dodge the rocks.
-- Survive 30 seconds to win. You have three lives; a rock that hits you costs one.

local LANES = { -2.5, 0, 2.5 }
local SURVIVE = 30
local lane = 2
local player
local speed = 7

local function show()
  ui.text("score", "Dodged " .. game.score, { x = 0.05, y = 0.04, size = 0.04, color = 5 })
  ui.bar("lives", game.lives, 3, { x = 0.05, y = 0.1, w = 0.3, h = 0.025, color = 2 })
end

local function spawn_rock()
  local l = rand_int(1, 3)
  world.spawn("box", { x = LANES[l], y = 9, w = 1.4, h = 1.4, d = 1.4, vy = -speed, color = 4, solid = true, tag = "rock" })
end

function init()
  world.bounds(9, 16)
  player = world.spawn("box", { x = LANES[lane], y = -6, w = 1.2, h = 1.2, d = 1.2, color = 1, solid = true, tag = "player" })
  world.camera{ mode = "chase", follow = player }
  game.lives = 3
  timer.every(0.7, spawn_rock)
  show()
end

function update(dt)
  speed = 7 + game.time * 0.1
  if game.time >= SURVIVE then
    game.win("You made it!")
  end
end

function on_tap(x, y)
  if x < 0 then
    lane = math.max(1, lane - 1)
  else
    lane = math.min(3, lane + 1)
  end
  player.x = LANES[lane]
end

function on_collide(a, b)
  local rock
  if a.tag == "rock" and b.tag == "player" then
    rock = a
  elseif b.tag == "rock" and a.tag == "player" then
    rock = b
  end
  if not rock then
    return
  end
  rock:destroy()
  game.lives = game.lives - 1
  show()
  if game.lives <= 0 then
    game.lose("You crashed")
  end
end

function on_exit(obj)
  if obj.tag == "rock" then
    obj:destroy()
    game.score = game.score + 1
    show()
  end
end
`,
  shooter: `-- Shooter (top-down 2D). Drag to move your ship; it fires on its own. Shoot 20 aliens to win.
-- An alien that reaches the bottom or hits your ship costs one of your three lives.

local TARGET = 20
local ship

local function show()
  ui.text("score", "Aliens " .. game.score .. " / " .. TARGET, { x = 0.05, y = 0.04, size = 0.045, color = 5 })
  ui.bar("lives", game.lives, 3, { x = 0.05, y = 0.1, w = 0.3, h = 0.025, color = 2 })
end

local function lose_life()
  game.lives = game.lives - 1
  show()
  if game.lives <= 0 then
    game.lose("Overrun")
  end
end

-- Returns the object with the first tag and the object with the second tag, whichever order they came in.
local function pair(a, b, first, second)
  if a.tag == first and b.tag == second then
    return a, b
  end
  if a.tag == second and b.tag == first then
    return b, a
  end
end

local function fire()
  world.spawn("box", { x = ship.x, y = ship.y + 0.9, w = 0.25, h = 0.7, d = 0.05, vy = 14, color = 3, solid = true, tag = "shot", life = 1.5 })
end

local function invade()
  world.spawn("cone", { x = rand() * 7 - 3.5, y = 9, w = 1, h = 1, d = 0.05, vy = -(2.5 + game.time * 0.05), color = 4, solid = true, tag = "alien" })
end

function init()
  world.bounds(9, 16)
  world.camera{ mode = "top2d" }
  ship = world.spawn("box", { x = 0, y = -6.5, w = 1, h = 1, d = 0.05, color = 1, solid = true, tag = "ship" })
  game.lives = 3
  timer.every(0.25, fire)
  timer.every(0.9, invade)
  show()
end

function on_hold(x, y)
  ship.x = math.max(-4, math.min(4, x))
end

function on_collide(a, b)
  local shot, alien = pair(a, b, "shot", "alien")
  if shot then
    shot:destroy()
    alien:destroy()
    game.score = game.score + 1
    show()
    if game.score >= TARGET then
      game.win("Earth is safe!")
    end
    return
  end
  local _, hitter = pair(a, b, "ship", "alien")
  if hitter then
    hitter:destroy()
    lose_life()
  end
end

function on_exit(obj)
  if obj.tag == "alien" then
    lose_life()
  end
  obj:destroy()
end
`,
  timing: `-- Timing (2D). A marker slides along the bar: tap when it is inside the green zone. Ten hits win.
-- A miss costs one of your three lives. The marker speeds up and the zone shrinks as you score.

local TARGET = 10
local marker
local zone
local direction = 1

local function show()
  ui.text("score", "Hits " .. game.score .. " / " .. TARGET, { x = 0.5, y = 0.05, size = 0.05, align = "center", color = 5 })
  ui.bar("lives", game.lives, 3, { x = 0.35, y = 0.12, w = 0.3, h = 0.03, color = 2 })
end

function init()
  world.bounds(9, 16)
  world.camera{ mode = "side2d" }
  world.spawn("box", { x = 0, y = 0, z = 1, w = 8, h = 0.4, d = 0.05, color = 2, tag = "track" })
  zone = world.spawn("box", { x = 0, y = 0, z = 0.5, w = 1.2, h = 0.9, d = 0.05, color = 4, tag = "zone" })
  marker = world.spawn("box", { x = -4, y = 0, z = 0, w = 0.3, h = 1.4, d = 0.05, color = 5, tag = "marker" })
  game.lives = 3
  show()
end

function update(dt)
  local speed = 5 + game.score * 0.6
  marker.x = marker.x + direction * speed * dt
  if marker.x > 4 then
    marker.x = 4
    direction = -1
  elseif marker.x < -4 then
    marker.x = -4
    direction = 1
  end
end

function on_tap(x, y)
  if math.abs(marker.x - zone.x) <= zone.w / 2 then
    game.score = game.score + 1
    zone.x = rand() * 6 - 3
    zone.w = math.max(0.8, 1.2 - game.score * 0.04)
    show()
    if game.score >= TARGET then
      game.win("Perfect timing!")
    end
  else
    game.lives = game.lives - 1
    show()
    if game.lives <= 0 then
      game.lose("Too many misses")
    end
  end
end
`,
};
